"""
TDD - TEST DRIVEN DEVELOPMENT - DESENVOLVIMENTO DIRIGIDO A TESTES
    DIVIDIDO EM: RED, GREEN E REFACTOR
    
    RED
        PARTE 1 - CRIAR O TESTE E VER FALHAR
        
    GREEN
        PARTE 2 - CRIAR O CÓDIGO E VER O TESTE PASSAR
        
    REFACTOR
        PARTE 3 - MELHORAR O CÓDIGO


1 - RECEBER UM NÚMERO INTEIRO;
2 - SABER SE O NUM É MULT DE 3 E 5
        RETORNAR 'BACON COM OVOS';
3 - SABER SE O NÚMERO NÃO É MULT DE 3 E 5
        RETORNAR 'PASSAR FOME';
4 - SABER SE O NÚMERO É MULT SOMENTE DE 3
        RETORNAR 'BACON';
5 - SABER SE O NÚMERO É MULT SOMENTE DE 5
        RETORNAR 'OVOS'.
"""

def bacon_com_ovos(n):
    assert isinstance(n, int), 'n deve ser um int'